const ayarlar = {
  TOKEN: "", // ASSAGIYI OKU
  sahip: "BOTUNUZUN SAHİP ID",
  prefix: "!"
};

module.exports = ayarlar;

//BOT TOKENINIZI EGER BOT GLITCHDE KALACAK
//ISE .ENV DOSYASINA
//EGER VDS YE KURACAK ISENIZ YUKARIYA 1. SATIRA YAZIN