const ayarlar = {
  sahip: "BOTUNUZUN SAHİP ID",
  prefix: "BOTUNUZUN ÖN EKİ"
};

module.exports = ayarlar;

//BOT TOKENINIZI EGER BOT GLITCHDE KALACAK 
//ISE .ENV DOSYASINA 
//EGER VDS YE KURACAK ISENIZ 1. SATIRIN ALTINA
//TOKEN: "BOT TOKENINIZ", SEKLINDE YAZIN!